/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package activity01;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

//import static org.junit.Assert.assertNotNull;

class AppTest {
    @Test void appHasAGreeting() {
        activity01.App classUnderTest = new activity01.App();
        Assertions.assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
