/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package activity01;

public class App {
    public String getGreeting() {
        return "Hello World!,...from getGreeting  >>>>>>>";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting()+ " ...from App");
    }
}
